#!/usr/bin/env bash
# Prompts for API keys and writes them to .env (skipped when .env already exists).
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env   : exists — skipping (edit manually to update keys)"
  exit 0
fi

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  First-time setup: configure your API keys           │"
echo "│  Keys are stored in .env (gitignored).               │"
echo "└──────────────────────────────────────────────────────┘"
echo ""

while true; do
  printf "HuggingFace token  (https://huggingface.co/settings/tokens): "
  read -r HF_TOKEN
  [ -n "$HF_TOKEN" ] && break
  echo "  Error: HuggingFace token is required."
done

while true; do
  printf "Anthropic API key  (https://console.anthropic.com/settings/keys): "
  read -r ANTHROPIC_API_KEY
  [ -n "$ANTHROPIC_API_KEY" ] && break
  echo "  Error: Anthropic API key is required."
done

cat > "$ENV_FILE" <<EOF
# Auto-generated by make install — edit freely.
HF_TOKEN=${HF_TOKEN}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Default provider and model (overridable via make cli PROVIDER=... MODEL=...)
PROVIDER=anthropic
MODEL=claude-opus-4-6
EOF

echo ""
echo ".env   : created"
