#!/usr/bin/env bash
# Jupyter environment setup:
#   1. Verify Python 3.9+
#   2. Create a virtualenv on macOS
#   3. Install all pip dependencies from requirements.txt
#   4. Ensure notebooks/ directory exists
#   5. Prompt for API keys (skipped when .env already exists)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── 1. Python check ───────────────────────────────────────────────────────────
PYTHON_BIN=""
for cmd in python3 python; do
  if command -v "$cmd" &>/dev/null; then
    ver=$("$cmd" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')" 2>/dev/null || true)
    major="${ver%%.*}"
    minor="${ver##*.}"
    if [ "${major:-0}" -ge 3 ] && [ "${minor:-0}" -ge 9 ]; then
      PYTHON_BIN="$cmd"
      break
    fi
  fi
done

if [ -z "$PYTHON_BIN" ]; then
  echo ""
  echo "Error: Python 3.9+ is required but not found."
  echo "  Install it from https://www.python.org/downloads/"
  exit 1
fi

echo "Python : $($PYTHON_BIN --version)"

# ── 2. macOS: create virtualenv ───────────────────────────────────────────────
OS="$(uname -s)"
VENV_DIR="$REPO_ROOT/.venv"
PIP_BIN="$(command -v pip3 || command -v pip || echo pip)"

if [ "$OS" = "Darwin" ]; then
  echo "macOS  : detected"
  if [ ! -d "$VENV_DIR" ]; then
    echo "venv   : creating at .venv …"
    "$PYTHON_BIN" -m venv "$VENV_DIR"
    echo "venv   : created"
  else
    echo "venv   : .venv already exists"
  fi
  PYTHON_BIN="$VENV_DIR/bin/python"
  PIP_BIN="$VENV_DIR/bin/pip"
fi

# ── 3. Install all pip dependencies ───────────────────────────────────────────
REQUIREMENTS="$REPO_ROOT/requirements.txt"
echo "deps   : installing from requirements.txt …"
"$PIP_BIN" install -r "$REQUIREMENTS" --quiet
echo "deps   : installed"

# ── 4. Ensure notebooks directory exists ──────────────────────────────────────
NOTEBOOKS_DIR="$REPO_ROOT/notebooks"
if [ ! -d "$NOTEBOOKS_DIR" ]; then
  mkdir -p "$NOTEBOOKS_DIR"
  echo "dir    : notebooks/ created"
else
  echo "dir    : notebooks/ already exists"
fi

# ── 5. API key setup (skipped when .env already exists) ───────────────────────
ENV_FILE="$REPO_ROOT/.env"

if [ -f "$ENV_FILE" ]; then
  echo ".env   : exists — skipping key setup (edit manually to update keys)"
  exit 0
fi

echo ""
echo "┌──────────────────────────────────────────────────────┐"
echo "│  First-time setup: configure your API keys           │"
echo "│  Keys are stored in .env (gitignored).               │"
echo "└──────────────────────────────────────────────────────┘"
echo ""

while true; do
  printf "HuggingFace token  (https://huggingface.co/settings/tokens): "
  read -r HF_TOKEN
  [ -n "$HF_TOKEN" ] && break
  echo "  Error: HuggingFace token is required."
done

while true; do
  printf "Anthropic API key  (https://console.anthropic.com/settings/keys): "
  read -r ANTHROPIC_API_KEY
  [ -n "$ANTHROPIC_API_KEY" ] && break
  echo "  Error: Anthropic API key is required."
done

cat > "$ENV_FILE" <<EOF
# Auto-generated by make install — edit freely.
HF_TOKEN=${HF_TOKEN}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Default provider and model (overridable via make cli PROVIDER=... MODEL=...)
PROVIDER=claude
MODEL=claude-opus-4-6
EOF

echo ""
echo ".env   : created."
